import './globals.css'
import { i18n } from 'i18n-config'
import { AppProvider } from '@utils/providers/AppProvider'
import { poppins } from '@styles/fonts/poppins'
import Header from '@components/global/Header'
import type { Metadata } from 'next'

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string }
}) => {
  return (
    <html lang={params.lang}>
      <body className={poppins.className}>
        <AppProvider>
          <Header />
          {children}
        </AppProvider>
      </body>
    </html>
  )
}

export default RootLayout
